spring.application.name=paymentservice

spring.data.mongodb.uri=${MONGO_DB_URI:mongodb://payment-db:27017/paymentdb?replicaSet=rs0}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.xml

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6381}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:kafka:9092}
spring.kafka.producer.key-serializer=${KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
spring.kafka.producer.value-serializer=${KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}


random.number.api.url=${RANDOM_NUMBER_API_URL:https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new}
