spring.data.mongodb.uri=${MONGO_DB_URI:mongodb://payment-db:27017/paymentdb?replicaSet=rs0}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6381}